
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.lightingfixtures.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.lightingfixtures.block.WatermeterBlock;
import net.mcreator.lightingfixtures.block.UhpecBlock;
import net.mcreator.lightingfixtures.block.TwoopenthreepinsocketBlock;
import net.mcreator.lightingfixtures.block.TungstenbulbsBlock;
import net.mcreator.lightingfixtures.block.TrackspotlightsBlock;
import net.mcreator.lightingfixtures.block.Trackspotlights1Block;
import net.mcreator.lightingfixtures.block.TrackBlock;
import net.mcreator.lightingfixtures.block.Track2Block;
import net.mcreator.lightingfixtures.block.ThreetubefluorescentlampBlock;
import net.mcreator.lightingfixtures.block.ThreeonswitchBlock;
import net.mcreator.lightingfixtures.block.ThreelampfluorescentlampwithlampshadeBlock;
import net.mcreator.lightingfixtures.block.ThemainheatingistheBlock;
import net.mcreator.lightingfixtures.block.ThemaincornerpipeoftheheaterBlock;
import net.mcreator.lightingfixtures.block.ThemainbranchpipeoftheheaterBlock;
import net.mcreator.lightingfixtures.block.TheheatingisBlock;
import net.mcreator.lightingfixtures.block.TVsocketBlock;
import net.mcreator.lightingfixtures.block.TVnetworksocketBlock;
import net.mcreator.lightingfixtures.block.TPFLSTBlock;
import net.mcreator.lightingfixtures.block.TPFLDTBlock;
import net.mcreator.lightingfixtures.block.SupermarketantitheftsystemBlock;
import net.mcreator.lightingfixtures.block.SupermarketSelfCheckoutSystemBlock;
import net.mcreator.lightingfixtures.block.SmokedetectorBlock;
import net.mcreator.lightingfixtures.block.SmalldownlightsBlock;
import net.mcreator.lightingfixtures.block.SingletubefluorescentlampwithlampshadeBlock;
import net.mcreator.lightingfixtures.block.SingletubefluorescentlampsBlock;
import net.mcreator.lightingfixtures.block.Singletubefluorescentlamps1Block;
import net.mcreator.lightingfixtures.block.SingleswitchswitchBlock;
import net.mcreator.lightingfixtures.block.SevenpinsocketBlock;
import net.mcreator.lightingfixtures.block.SLEDbcBlock;
import net.mcreator.lightingfixtures.block.RainCSBlock;
import net.mcreator.lightingfixtures.block.QuadrupleswitchBlock;
import net.mcreator.lightingfixtures.block.PsgBlock;
import net.mcreator.lightingfixtures.block.PSGBBlock;
import net.mcreator.lightingfixtures.block.PSGABlock;
import net.mcreator.lightingfixtures.block.OtembwaemBlock;
import net.mcreator.lightingfixtures.block.OneopenthreepinsocketBlock;
import net.mcreator.lightingfixtures.block.OembwsmBlock;
import net.mcreator.lightingfixtures.block.OembwfmBlock;
import net.mcreator.lightingfixtures.block.OVEMVLCDBlock;
import net.mcreator.lightingfixtures.block.OVEMVLCD2Block;
import net.mcreator.lightingfixtures.block.OVEMVBlock;
import net.mcreator.lightingfixtures.block.OVEMV2Block;
import net.mcreator.lightingfixtures.block.OTEMBWTMBlock;
import net.mcreator.lightingfixtures.block.OEMBWTMBlock;
import net.mcreator.lightingfixtures.block.MetalhalidefloodlightsBlock;
import net.mcreator.lightingfixtures.block.MetalhalidefloodlightBlock;
import net.mcreator.lightingfixtures.block.MediumdownlightBlock;
import net.mcreator.lightingfixtures.block.MLEDbcBlock;
import net.mcreator.lightingfixtures.block.LargecylinderlampBlock;
import net.mcreator.lightingfixtures.block.LampwarmthbathBlock;
import net.mcreator.lightingfixtures.block.LLEDbcBlock;
import net.mcreator.lightingfixtures.block.LETFLSBlock;
import net.mcreator.lightingfixtures.block.LETFLLBlock;
import net.mcreator.lightingfixtures.block.LEDpanellightBlock;
import net.mcreator.lightingfixtures.block.LEDilhBlock;
import net.mcreator.lightingfixtures.block.LEDfloodlightsBlock;
import net.mcreator.lightingfixtures.block.LEDcanopylight2X2Block;
import net.mcreator.lightingfixtures.block.LEDcanopylight1X2Block;
import net.mcreator.lightingfixtures.block.LEDFloodLightTopBlock;
import net.mcreator.lightingfixtures.block.IodinetungstenlampBlock;
import net.mcreator.lightingfixtures.block.InternetoutletsBlock;
import net.mcreator.lightingfixtures.block.HighpoweroutletsBlock;
import net.mcreator.lightingfixtures.block.HighpowerelectricmeterboxBlock;
import net.mcreator.lightingfixtures.block.HeatingsupervisorBlock;
import net.mcreator.lightingfixtures.block.HeatingpipesBlock;
import net.mcreator.lightingfixtures.block.HeatingpipeBlock;
import net.mcreator.lightingfixtures.block.HeatingmainvalveBlock;
import net.mcreator.lightingfixtures.block.HeatinginterconnectionpipesBlock;
import net.mcreator.lightingfixtures.block.HeatingcBlock;
import net.mcreator.lightingfixtures.block.HeatingbranchpipeBlock;
import net.mcreator.lightingfixtures.block.HeatingbleedvalveBlock;
import net.mcreator.lightingfixtures.block.HeatingbBlock;
import net.mcreator.lightingfixtures.block.HeatingaBlock;
import net.mcreator.lightingfixtures.block.HFSBlock;
import net.mcreator.lightingfixtures.block.HFBHBlock;
import net.mcreator.lightingfixtures.block.GasmetersBlock;
import net.mcreator.lightingfixtures.block.FourtubefluorescentlightwithlampshadeBlock;
import net.mcreator.lightingfixtures.block.FourtubefluorescentlampBlock;
import net.mcreator.lightingfixtures.block.FluorescentluminairesBlock;
import net.mcreator.lightingfixtures.block.FluorescentlightsforclassroomsBlock;
import net.mcreator.lightingfixtures.block.FluorescentlightbulbsBlock;
import net.mcreator.lightingfixtures.block.FluorescentlampholdersBlock;
import net.mcreator.lightingfixtures.block.FluorescentdoublebracketBlock;
import net.mcreator.lightingfixtures.block.FluorescentceilinglightsBlock;
import net.mcreator.lightingfixtures.block.Fluorescentceilinglights2Block;
import net.mcreator.lightingfixtures.block.Fluorescentceilinglights1Block;
import net.mcreator.lightingfixtures.block.FivepinsocketBlock;
import net.mcreator.lightingfixtures.block.FireemergencylightBlock;
import net.mcreator.lightingfixtures.block.FireAlarmButtonBlock;
import net.mcreator.lightingfixtures.block.EslmBlock;
import net.mcreator.lightingfixtures.block.EnergysavinlamplargeBlock;
import net.mcreator.lightingfixtures.block.EnergysavinglampmediumBlock;
import net.mcreator.lightingfixtures.block.ElectronicsingletubefluorescentampsBlock;
import net.mcreator.lightingfixtures.block.ElectronicdoubletubefluorescentlampsBlock;
import net.mcreator.lightingfixtures.block.Electricalcabinets2x3Block;
import net.mcreator.lightingfixtures.block.Electricalcabinets2x2Block;
import net.mcreator.lightingfixtures.block.Electricalcabinets1x2380Block;
import net.mcreator.lightingfixtures.block.Electricalcabinets1x1Block;
import net.mcreator.lightingfixtures.block.Electricalcabinets1x1380Block;
import net.mcreator.lightingfixtures.block.Electricalcabinets1X2Block;
import net.mcreator.lightingfixtures.block.ElectricalboxwithelectricitymeterBlock;
import net.mcreator.lightingfixtures.block.Electricalboxwithelectricitymeter2x3Block;
import net.mcreator.lightingfixtures.block.Electricalboxwithelectricitymeter2x380Block;
import net.mcreator.lightingfixtures.block.Electricalboxwithelectricitymeter2x2Block;
import net.mcreator.lightingfixtures.block.Electricalboxwithelectricitymeter2x1Block;
import net.mcreator.lightingfixtures.block.Electricalboxwithelectricitymeter1x1Block;
import net.mcreator.lightingfixtures.block.EbwemLCDBlock;
import net.mcreator.lightingfixtures.block.Ebwem2X3LCDBlock;
import net.mcreator.lightingfixtures.block.ESLSBlock;
import net.mcreator.lightingfixtures.block.ESLLBlock;
import net.mcreator.lightingfixtures.block.EPLSTBlock;
import net.mcreator.lightingfixtures.block.EPLEHBBlock;
import net.mcreator.lightingfixtures.block.EPLDTBlock;
import net.mcreator.lightingfixtures.block.EBWEMBlock;
import net.mcreator.lightingfixtures.block.DualnetworkoutletsBlock;
import net.mcreator.lightingfixtures.block.DtubeceilinglightBlock;
import net.mcreator.lightingfixtures.block.DoubletubesinglestandfluorescentlampwithlampshadeBlock;
import net.mcreator.lightingfixtures.block.DoubletubefluorescentlampwithlampshadeBlock;
import net.mcreator.lightingfixtures.block.DoubletubefluorescentlampsBlock;
import net.mcreator.lightingfixtures.block.DoubletubeceilinglightBlock;
import net.mcreator.lightingfixtures.block.DoubleopenswitchBlock;
import net.mcreator.lightingfixtures.block.CornertypefluorescentlampBlock;
import net.mcreator.lightingfixtures.block.ClassroomLEDLightsBlock;
import net.mcreator.lightingfixtures.block.CemospalcepaBlock;
import net.mcreator.lightingfixtures.block.CeilingBlock;
import net.mcreator.lightingfixtures.block.AluminumtubesarefluorescentBlock;
import net.mcreator.lightingfixtures.block.Aluminumtubesarefluorescent2Block;
import net.mcreator.lightingfixtures.block.AluminumgussetBlock;
import net.mcreator.lightingfixtures.block.Aluminumgusset2X2Block;
import net.mcreator.lightingfixtures.block.Aluminumgusset1X2Block;
import net.mcreator.lightingfixtures.block.AluminumGrilleBlock;
import net.mcreator.lightingfixtures.block.AluminumGrille2Block;
import net.mcreator.lightingfixtures.block.AccesscontrolintercomhostBlock;
import net.mcreator.lightingfixtures.block.AccesscontrolintercomextensionONBlock;
import net.mcreator.lightingfixtures.block.AccesscontrolintercomextensionBlock;
import net.mcreator.lightingfixtures.LightingfixturesMod;

public class LightingfixturesModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, LightingfixturesMod.MODID);
	public static final RegistryObject<Block> CEILING = REGISTRY.register("ceiling", () -> new CeilingBlock());
	public static final RegistryObject<Block> SINGLETUBEFLUORESCENTLAMPS = REGISTRY.register("singletubefluorescentlamps", () -> new SingletubefluorescentlampsBlock());
	public static final RegistryObject<Block> SINGLETUBEFLUORESCENTLAMPS_1 = REGISTRY.register("singletubefluorescentlamps_1", () -> new Singletubefluorescentlamps1Block());
	public static final RegistryObject<Block> DOUBLETUBEFLUORESCENTLAMPS = REGISTRY.register("doubletubefluorescentlamps", () -> new DoubletubefluorescentlampsBlock());
	public static final RegistryObject<Block> THREETUBEFLUORESCENTLAMP = REGISTRY.register("threetubefluorescentlamp", () -> new ThreetubefluorescentlampBlock());
	public static final RegistryObject<Block> FLUORESCENTLIGHTSFORCLASSROOMS = REGISTRY.register("fluorescentlightsforclassrooms", () -> new FluorescentlightsforclassroomsBlock());
	public static final RegistryObject<Block> CLASSROOM_LED_LIGHTS = REGISTRY.register("classroom_led_lights", () -> new ClassroomLEDLightsBlock());
	public static final RegistryObject<Block> FLUORESCENTLIGHTBULBS = REGISTRY.register("fluorescentlightbulbs", () -> new FluorescentlightbulbsBlock());
	public static final RegistryObject<Block> LE_DPANELLIGHT = REGISTRY.register("le_dpanellight", () -> new LEDpanellightBlock());
	public static final RegistryObject<Block> LE_DCANOPYLIGHT_1_X_2 = REGISTRY.register("le_dcanopylight_1_x_2", () -> new LEDcanopylight1X2Block());
	public static final RegistryObject<Block> LE_DCANOPYLIGHT_2_X_2 = REGISTRY.register("le_dcanopylight_2_x_2", () -> new LEDcanopylight2X2Block());
	public static final RegistryObject<Block> ALUMINUMGUSSET = REGISTRY.register("aluminumgusset", () -> new AluminumgussetBlock());
	public static final RegistryObject<Block> ALUMINUMGUSSET_1_X_2 = REGISTRY.register("aluminumgusset_1_x_2", () -> new Aluminumgusset1X2Block());
	public static final RegistryObject<Block> ALUMINUMGUSSET_2_X_2 = REGISTRY.register("aluminumgusset_2_x_2", () -> new Aluminumgusset2X2Block());
	public static final RegistryObject<Block> FLUORESCENTCEILINGLIGHTS = REGISTRY.register("fluorescentceilinglights", () -> new FluorescentceilinglightsBlock());
	public static final RegistryObject<Block> FLUORESCENTCEILINGLIGHTS_2 = REGISTRY.register("fluorescentceilinglights_2", () -> new Fluorescentceilinglights2Block());
	public static final RegistryObject<Block> FLUORESCENTCEILINGLIGHTS_1 = REGISTRY.register("fluorescentceilinglights_1", () -> new Fluorescentceilinglights1Block());
	public static final RegistryObject<Block> SINGLESWITCHSWITCH = REGISTRY.register("singleswitchswitch", () -> new SingleswitchswitchBlock());
	public static final RegistryObject<Block> DOUBLEOPENSWITCH = REGISTRY.register("doubleopenswitch", () -> new DoubleopenswitchBlock());
	public static final RegistryObject<Block> THREEONSWITCH = REGISTRY.register("threeonswitch", () -> new ThreeonswitchBlock());
	public static final RegistryObject<Block> QUADRUPLESWITCH = REGISTRY.register("quadrupleswitch", () -> new QuadrupleswitchBlock());
	public static final RegistryObject<Block> LE_DFLOODLIGHTS = REGISTRY.register("le_dfloodlights", () -> new LEDfloodlightsBlock());
	public static final RegistryObject<Block> LED_FLOOD_LIGHT_TOP = REGISTRY.register("led_flood_light_top", () -> new LEDFloodLightTopBlock());
	public static final RegistryObject<Block> LARGECYLINDERLAMP = REGISTRY.register("largecylinderlamp", () -> new LargecylinderlampBlock());
	public static final RegistryObject<Block> MEDIUMDOWNLIGHT = REGISTRY.register("mediumdownlight", () -> new MediumdownlightBlock());
	public static final RegistryObject<Block> SMALLDOWNLIGHTS = REGISTRY.register("smalldownlights", () -> new SmalldownlightsBlock());
	public static final RegistryObject<Block> ELECTRONICSINGLETUBEFLUORESCENTAMPS = REGISTRY.register("electronicsingletubefluorescentamps", () -> new ElectronicsingletubefluorescentampsBlock());
	public static final RegistryObject<Block> ELECTRONICDOUBLETUBEFLUORESCENTLAMPS = REGISTRY.register("electronicdoubletubefluorescentlamps", () -> new ElectronicdoubletubefluorescentlampsBlock());
	public static final RegistryObject<Block> TRACKSPOTLIGHTS = REGISTRY.register("trackspotlights", () -> new TrackspotlightsBlock());
	public static final RegistryObject<Block> TRACKSPOTLIGHTS_1 = REGISTRY.register("trackspotlights_1", () -> new Trackspotlights1Block());
	public static final RegistryObject<Block> METALHALIDEFLOODLIGHTS = REGISTRY.register("metalhalidefloodlights", () -> new MetalhalidefloodlightsBlock());
	public static final RegistryObject<Block> METALHALIDEFLOODLIGHT = REGISTRY.register("metalhalidefloodlight", () -> new MetalhalidefloodlightBlock());
	public static final RegistryObject<Block> FLUORESCENTLUMINAIRES = REGISTRY.register("fluorescentluminaires", () -> new FluorescentluminairesBlock());
	public static final RegistryObject<Block> ALUMINUMTUBESAREFLUORESCENT = REGISTRY.register("aluminumtubesarefluorescent", () -> new AluminumtubesarefluorescentBlock());
	public static final RegistryObject<Block> ENERGYSAVINGLAMPMEDIUM = REGISTRY.register("energysavinglampmedium", () -> new EnergysavinglampmediumBlock());
	public static final RegistryObject<Block> ENERGYSAVINLAMPLARGE = REGISTRY.register("energysavinlamplarge", () -> new EnergysavinlamplargeBlock());
	public static final RegistryObject<Block> ONEOPENTHREEPINSOCKET = REGISTRY.register("oneopenthreepinsocket", () -> new OneopenthreepinsocketBlock());
	public static final RegistryObject<Block> TWOOPENTHREEPINSOCKET = REGISTRY.register("twoopenthreepinsocket", () -> new TwoopenthreepinsocketBlock());
	public static final RegistryObject<Block> SEVENPINSOCKET = REGISTRY.register("sevenpinsocket", () -> new SevenpinsocketBlock());
	public static final RegistryObject<Block> T_VSOCKET = REGISTRY.register("t_vsocket", () -> new TVsocketBlock());
	public static final RegistryObject<Block> INTERNETOUTLETS = REGISTRY.register("internetoutlets", () -> new InternetoutletsBlock());
	public static final RegistryObject<Block> GASMETERS = REGISTRY.register("gasmeters", () -> new GasmetersBlock());
	public static final RegistryObject<Block> RAIN_CS = REGISTRY.register("rain_cs", () -> new RainCSBlock());
	public static final RegistryObject<Block> ELECTRICALCABINETS_1X_1 = REGISTRY.register("electricalcabinets_1x_1", () -> new Electricalcabinets1x1Block());
	public static final RegistryObject<Block> ELECTRICALCABINETS_1_X_2 = REGISTRY.register("electricalcabinets_1_x_2", () -> new Electricalcabinets1X2Block());
	public static final RegistryObject<Block> ELECTRICALCABINETS_2X_2 = REGISTRY.register("electricalcabinets_2x_2", () -> new Electricalcabinets2x2Block());
	public static final RegistryObject<Block> ELECTRICALCABINETS_2X_3 = REGISTRY.register("electricalcabinets_2x_3", () -> new Electricalcabinets2x3Block());
	public static final RegistryObject<Block> ELECTRICALBOXWITHELECTRICITYMETER = REGISTRY.register("electricalboxwithelectricitymeter", () -> new ElectricalboxwithelectricitymeterBlock());
	public static final RegistryObject<Block> ELECTRICALBOXWITHELECTRICITYMETER_1X_1 = REGISTRY.register("electricalboxwithelectricitymeter_1x_1", () -> new Electricalboxwithelectricitymeter1x1Block());
	public static final RegistryObject<Block> ELECTRICALBOXWITHELECTRICITYMETER_2X_1 = REGISTRY.register("electricalboxwithelectricitymeter_2x_1", () -> new Electricalboxwithelectricitymeter2x1Block());
	public static final RegistryObject<Block> ELECTRICALBOXWITHELECTRICITYMETER_2X_2 = REGISTRY.register("electricalboxwithelectricitymeter_2x_2", () -> new Electricalboxwithelectricitymeter2x2Block());
	public static final RegistryObject<Block> ACCESSCONTROLINTERCOMHOST = REGISTRY.register("accesscontrolintercomhost", () -> new AccesscontrolintercomhostBlock());
	public static final RegistryObject<Block> ACCESSCONTROLINTERCOMEXTENSION = REGISTRY.register("accesscontrolintercomextension", () -> new AccesscontrolintercomextensionBlock());
	public static final RegistryObject<Block> IODINETUNGSTENLAMP = REGISTRY.register("iodinetungstenlamp", () -> new IodinetungstenlampBlock());
	public static final RegistryObject<Block> DOUBLETUBECEILINGLIGHT = REGISTRY.register("doubletubeceilinglight", () -> new DoubletubeceilinglightBlock());
	public static final RegistryObject<Block> DTUBECEILINGLIGHT = REGISTRY.register("dtubeceilinglight", () -> new DtubeceilinglightBlock());
	public static final RegistryObject<Block> ACCESSCONTROLINTERCOMEXTENSION_ON = REGISTRY.register("accesscontrolintercomextension_on", () -> new AccesscontrolintercomextensionONBlock());
	public static final RegistryObject<Block> SINGLE_TUBE_FLUORESCENT_LAMP_WITH_LAMPSHADE = REGISTRY.register("single_tube_fluorescent_lamp_with_lampshade", () -> new SingletubefluorescentlampwithlampshadeBlock());
	public static final RegistryObject<Block> DOUBLE_TUBE_SINGLESTAND_FLUORESCENT_LAMP_WITH_LAMPSHADE = REGISTRY.register("double_tube_singlestand_fluorescent_lamp_with_lampshade", () -> new DoubletubesinglestandfluorescentlampwithlampshadeBlock());
	public static final RegistryObject<Block> DOUBLE_TUBE_FLUORESCENT_LAMPWITH_LAMPSHADE = REGISTRY.register("double_tube_fluorescent_lampwith_lampshade", () -> new DoubletubefluorescentlampwithlampshadeBlock());
	public static final RegistryObject<Block> THREE_LAMP_FLUORESCENT_LAMPWITH_LAMPSHADE = REGISTRY.register("three_lamp_fluorescent_lampwith_lampshade", () -> new ThreelampfluorescentlampwithlampshadeBlock());
	public static final RegistryObject<Block> FLUORESCENT_LAMP_HOLDERS = REGISTRY.register("fluorescent_lamp_holders", () -> new FluorescentlampholdersBlock());
	public static final RegistryObject<Block> FLUORESCENTDOUBLEBRACKET = REGISTRY.register("fluorescentdoublebracket", () -> new FluorescentdoublebracketBlock());
	public static final RegistryObject<Block> ELECTRICALBOXWITHELECTRICITYMETER_2X_3 = REGISTRY.register("electricalboxwithelectricitymeter_2x_3", () -> new Electricalboxwithelectricitymeter2x3Block());
	public static final RegistryObject<Block> ELECTRICALBOXWITHELECTRICITYMETER_2X_380 = REGISTRY.register("electricalboxwithelectricitymeter_2x_380", () -> new Electricalboxwithelectricitymeter2x380Block());
	public static final RegistryObject<Block> TUNGSTENBULBS = REGISTRY.register("tungstenbulbs", () -> new TungstenbulbsBlock());
	public static final RegistryObject<Block> WATERMETER = REGISTRY.register("watermeter", () -> new WatermeterBlock());
	public static final RegistryObject<Block> FIVEPINSOCKET = REGISTRY.register("fivepinsocket", () -> new FivepinsocketBlock());
	public static final RegistryObject<Block> T_VNETWORKSOCKET = REGISTRY.register("t_vnetworksocket", () -> new TVnetworksocketBlock());
	public static final RegistryObject<Block> DUALNETWORKOUTLETS = REGISTRY.register("dualnetworkoutlets", () -> new DualnetworkoutletsBlock());
	public static final RegistryObject<Block> HIGHPOWEROUTLETS = REGISTRY.register("highpoweroutlets", () -> new HighpoweroutletsBlock());
	public static final RegistryObject<Block> HEATINGPIPES = REGISTRY.register("heatingpipes", () -> new HeatingpipesBlock());
	public static final RegistryObject<Block> HEATINGPIPE = REGISTRY.register("heatingpipe", () -> new HeatingpipeBlock());
	public static final RegistryObject<Block> HEATINGBRANCHPIPE = REGISTRY.register("heatingbranchpipe", () -> new HeatingbranchpipeBlock());
	public static final RegistryObject<Block> THEHEATINGIS = REGISTRY.register("theheatingis", () -> new TheheatingisBlock());
	public static final RegistryObject<Block> HEATINGINTERCONNECTIONPIPES = REGISTRY.register("heatinginterconnectionpipes", () -> new HeatinginterconnectionpipesBlock());
	public static final RegistryObject<Block> THEMAINCORNERPIPEOFTHEHEATER = REGISTRY.register("themaincornerpipeoftheheater", () -> new ThemaincornerpipeoftheheaterBlock());
	public static final RegistryObject<Block> THEMAINHEATINGISTHE = REGISTRY.register("themainheatingisthe", () -> new ThemainheatingistheBlock());
	public static final RegistryObject<Block> THEMAINBRANCHPIPEOFTHEHEATER = REGISTRY.register("themainbranchpipeoftheheater", () -> new ThemainbranchpipeoftheheaterBlock());
	public static final RegistryObject<Block> HEATINGSUPERVISOR = REGISTRY.register("heatingsupervisor", () -> new HeatingsupervisorBlock());
	public static final RegistryObject<Block> HEATINGMAINVALVE = REGISTRY.register("heatingmainvalve", () -> new HeatingmainvalveBlock());
	public static final RegistryObject<Block> HEATINGBLEEDVALVE = REGISTRY.register("heatingbleedvalve", () -> new HeatingbleedvalveBlock());
	public static final RegistryObject<Block> HEATINGA = REGISTRY.register("heatinga", () -> new HeatingaBlock());
	public static final RegistryObject<Block> HEATINGB = REGISTRY.register("heatingb", () -> new HeatingbBlock());
	public static final RegistryObject<Block> HEATINGC = REGISTRY.register("heatingc", () -> new HeatingcBlock());
	public static final RegistryObject<Block> LAMPWARMTHBATH = REGISTRY.register("lampwarmthbath", () -> new LampwarmthbathBlock());
	public static final RegistryObject<Block> CEMOSPALCEPA = REGISTRY.register("cemospalcepa", () -> new CemospalcepaBlock());
	public static final RegistryObject<Block> FIRE_EMERGENCY_LIGHT = REGISTRY.register("fire_emergency_light", () -> new FireemergencylightBlock());
	public static final RegistryObject<Block> SMOKE_DETECTOR = REGISTRY.register("smoke_detector", () -> new SmokedetectorBlock());
	public static final RegistryObject<Block> FIRE_ALARM_BUTTON = REGISTRY.register("fire_alarm_button", () -> new FireAlarmButtonBlock());
	public static final RegistryObject<Block> ALUMINUM_GRILLE = REGISTRY.register("aluminum_grille", () -> new AluminumGrilleBlock());
	public static final RegistryObject<Block> ALUMINUM_GRILLE_2 = REGISTRY.register("aluminum_grille_2", () -> new AluminumGrille2Block());
	public static final RegistryObject<Block> ALUMINUM_TUBESARE_FLUORESCENT_2 = REGISTRY.register("aluminum_tubesare_fluorescent_2", () -> new Aluminumtubesarefluorescent2Block());
	public static final RegistryObject<Block> SUPERMARKE_TANTITHEFT_SYSTEM = REGISTRY.register("supermarke_tantitheft_system", () -> new SupermarketantitheftsystemBlock());
	public static final RegistryObject<Block> SUPERMARKET_SELF_CHECKOUT_SYSTEM = REGISTRY.register("supermarket_self_checkout_system", () -> new SupermarketSelfCheckoutSystemBlock());
	public static final RegistryObject<Block> HIGH_POWER_ELECTRIC_METER_BOX = REGISTRY.register("high_power_electric_meter_box", () -> new HighpowerelectricmeterboxBlock());
	public static final RegistryObject<Block> ELECTRICAL_CABINETS_1X1_380 = REGISTRY.register("electrical_cabinets_1x1_380", () -> new Electricalcabinets1x1380Block());
	public static final RegistryObject<Block> ELECTRICAL_CABINETS_1X2_380 = REGISTRY.register("electrical_cabinets_1x2_380", () -> new Electricalcabinets1x2380Block());
	public static final RegistryObject<Block> CORNER_TYPE_FLUORESCENT_LAMP = REGISTRY.register("corner_type_fluorescent_lamp", () -> new CornertypefluorescentlampBlock());
	public static final RegistryObject<Block> FOUR_TUBE_FLUORESCENT_LAMP = REGISTRY.register("four_tube_fluorescent_lamp", () -> new FourtubefluorescentlampBlock());
	public static final RegistryObject<Block> FOUR_TUBE_FLUORESCENT_LIGHT_WITH_LAMPSHADE = REGISTRY.register("four_tube_fluorescent_light_with_lampshade", () -> new FourtubefluorescentlightwithlampshadeBlock());
	public static final RegistryObject<Block> TRACK = REGISTRY.register("track", () -> new TrackBlock());
	public static final RegistryObject<Block> TRACK_2 = REGISTRY.register("track_2", () -> new Track2Block());
	public static final RegistryObject<Block> UHPEC = REGISTRY.register("uhpec", () -> new UhpecBlock());
	public static final RegistryObject<Block> PSG = REGISTRY.register("psg", () -> new PsgBlock());
	public static final RegistryObject<Block> PSGA = REGISTRY.register("psga", () -> new PSGABlock());
	public static final RegistryObject<Block> PSGB = REGISTRY.register("psgb", () -> new PSGBBlock());
	public static final RegistryObject<Block> OTEMBWTM = REGISTRY.register("otembwtm", () -> new OTEMBWTMBlock());
	public static final RegistryObject<Block> EBWEM = REGISTRY.register("ebwem", () -> new EBWEMBlock());
	public static final RegistryObject<Block> OEMBWTM = REGISTRY.register("oembwtm", () -> new OEMBWTMBlock());
	public static final RegistryObject<Block> OEMBWSM = REGISTRY.register("oembwsm", () -> new OembwsmBlock());
	public static final RegistryObject<Block> OEMBWFM = REGISTRY.register("oembwfm", () -> new OembwfmBlock());
	public static final RegistryObject<Block> OTEMBWAEM = REGISTRY.register("otembwaem", () -> new OtembwaemBlock());
	public static final RegistryObject<Block> OVEMV = REGISTRY.register("ovemv", () -> new OVEMVBlock());
	public static final RegistryObject<Block> OVEMV_2 = REGISTRY.register("ovemv_2", () -> new OVEMV2Block());
	public static final RegistryObject<Block> TPFLST = REGISTRY.register("tpflst", () -> new TPFLSTBlock());
	public static final RegistryObject<Block> TPFLDT = REGISTRY.register("tpfldt", () -> new TPFLDTBlock());
	public static final RegistryObject<Block> EPLST = REGISTRY.register("eplst", () -> new EPLSTBlock());
	public static final RegistryObject<Block> EPLDT = REGISTRY.register("epldt", () -> new EPLDTBlock());
	public static final RegistryObject<Block> EPLEHB = REGISTRY.register("eplehb", () -> new EPLEHBBlock());
	public static final RegistryObject<Block> LETFLL = REGISTRY.register("letfll", () -> new LETFLLBlock());
	public static final RegistryObject<Block> LETFLS = REGISTRY.register("letfls", () -> new LETFLSBlock());
	public static final RegistryObject<Block> HFBH = REGISTRY.register("hfbh", () -> new HFBHBlock());
	public static final RegistryObject<Block> HFS = REGISTRY.register("hfs", () -> new HFSBlock());
	public static final RegistryObject<Block> EBWEM_2_X_3_LCD = REGISTRY.register("ebwem_2_x_3_lcd", () -> new Ebwem2X3LCDBlock());
	public static final RegistryObject<Block> EBWEM_LCD = REGISTRY.register("ebwem_lcd", () -> new EbwemLCDBlock());
	public static final RegistryObject<Block> OVEMVLCD = REGISTRY.register("ovemvlcd", () -> new OVEMVLCDBlock());
	public static final RegistryObject<Block> OVEMVLCD_2 = REGISTRY.register("ovemvlcd_2", () -> new OVEMVLCD2Block());
	public static final RegistryObject<Block> ESLS = REGISTRY.register("esls", () -> new ESLSBlock());
	public static final RegistryObject<Block> ESLL = REGISTRY.register("esll", () -> new ESLLBlock());
	public static final RegistryObject<Block> ESLM = REGISTRY.register("eslm", () -> new EslmBlock());
	public static final RegistryObject<Block> LE_DILH = REGISTRY.register("le_dilh", () -> new LEDilhBlock());
	public static final RegistryObject<Block> SLE_DBC = REGISTRY.register("sle_dbc", () -> new SLEDbcBlock());
	public static final RegistryObject<Block> MLE_DBC = REGISTRY.register("mle_dbc", () -> new MLEDbcBlock());
	public static final RegistryObject<Block> LLE_DBC = REGISTRY.register("lle_dbc", () -> new LLEDbcBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
